# Generated by Django 4.2.7 on 2023-11-17 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastreRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastre_number', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('external_server_response', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.BooleanField()),
                ('response_timestamp', models.DateTimeField(auto_now_add=True)),
                ('cadastre_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_response', to='general.cadastrerequest')),
            ],
        ),
    ]
